// Generated by Apple Swift version 6.2.1 effective-5.10 (swiftlang-6.2.1.4.8 clang-1700.4.4.1)
#ifndef STTEXTVIEW_SWIFT_H
#define STTEXTVIEW_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wnon-modular-include-in-framework-module"
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#pragma clang diagnostic pop
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef unsigned char char8_t;
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import AppKit;
@import CoreFoundation;
@import Foundation;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"
#pragma clang diagnostic ignored "-Wunsafe-buffer-usage"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="STTextView",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

@class NSCoder;
@class NSRulerMarker;
@class NSScrollView;
/// A ruler view to display line numbers to the side of the text view.
SWIFT_CLASS("_TtC10STTextView21STLineNumberRulerView")
@interface STLineNumberRulerView : NSRulerView
@property (nonatomic) CGFloat reservedThicknessForMarkers;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER;
- (void)invalidateHashMarks;
- (void)addMarker:(NSRulerMarker * _Nonnull)marker;
- (void)drawHashMarksAndLabelsInRect:(NSRect)rect;
- (void)drawRect:(NSRect)dirtyRect;
- (nonnull instancetype)initWithScrollView:(NSScrollView * _Nullable)scrollView orientation:(NSRulerOrientation)orientation SWIFT_UNAVAILABLE;
@end

@class NSImage;
SWIFT_CLASS("_TtC10STTextView13STRulerMarker")
@interface STRulerMarker : NSRulerMarker
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (nonnull instancetype)initWithRulerView:(NSRulerView * _Nonnull)ruler markerLocation:(CGFloat)location image:(NSImage * _Nonnull)image imageOrigin:(NSPoint)imageOrigin SWIFT_UNAVAILABLE;
@end

@class NSColor;
@class NSFont;
@class NSParagraphStyle;
@class NSString;
@class NSAttributedString;
@class NSTextLayoutManager;
@class NSTextContentManager;
@class NSMenu;
/// A TextKit2 text view without NSTextView baggage
SWIFT_CLASS("_TtC10STTextView10STTextView")
@interface STTextView : NSView <NSTextContent, NSTextInput>
/// A Boolean value that controls whether the text view allows the user to edit text.
@property (nonatomic) BOOL isEditable;
/// A Boolean value that controls whether the text views allows the user to select text.
@property (nonatomic) BOOL isSelectable;
@property (nonatomic, readonly) BOOL isRichText;
@property (nonatomic, readonly) BOOL isFieldEditor;
@property (nonatomic, readonly) BOOL importsGraphics;
/// The color of the insertion point.
@property (nonatomic, strong) NSColor * _Nonnull insertionPointColor;
/// The font of the text.
/// This property applies to the entire text string.
/// Assigning a new value to this property causes the new font to be applied to the entire contents of the text view.
@property (nonatomic, strong) NSFont * _Nullable font;
/// The text color of the text view.
@property (nonatomic, strong) NSColor * _Nullable textColor;
/// The receiver’s default paragraph style.
@property (nonatomic, strong) NSParagraphStyle * _Nullable defaultParagraphStyle;
/// The attributes to apply to new text that the user enters.
/// This dictionary contains the attribute keys (and corresponding values) to apply to newly typed text.
/// When the text view’s selection changes, the contents of the dictionary are reset automatically.
@property (nonatomic, copy) NSDictionary<NSAttributedStringKey, id> * _Nonnull typingAttributes;
/// The characters of the receiver’s text.
/// For performance reasons, this value is the current backing store of the text object.
/// If you want to maintain a snapshot of this as you manipulate the text storage, you should make a copy of the appropriate substring.
@property (nonatomic, copy) NSString * _Nonnull string;
/// Replaces the receiver’s entire contents with the characters and attributes of the given attributed string.
- (void)setAttributedString:(NSAttributedString * _Nonnull)attributedString;
/// A Boolean that controls whether the text container adjusts the width of its bounding rectangle when its text view resizes.
/// When the value of this property is <code>true</code>, the text container adjusts its width when the width of its text view changes. The default value of this property is <code>false</code>.
/// note:
/// If you set both <code>widthTracksTextView</code> and <code>isHorizontallyResizable</code> up to resize automatically in the same dimension, your application can get trapped in an infinite loop.
/// seealso:
/// <a href="https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/TextStorageLayer/Tasks/TrackingSize.html#//apple_ref/doc/uid/20000927-CJBBIAAF">Tracking the Size of a Text View</a>
@property (nonatomic) BOOL widthTracksTextView;
/// A Boolean that controls whether the receiver changes its width to fit the width of its text.
@property (nonatomic) BOOL isHorizontallyResizable;
/// A Boolean that controls whether the text container adjusts the height of its bounding rectangle when its text view resizes.
/// When the value of this property is <code>true</code>, the text container adjusts its height when the height of its text view changes. The default value of this property is <code>false</code>.
/// note:
/// If you set both <code>heightTracksTextView</code> and <code>isVerticallyResizable</code> up to resize automatically in the same dimension, your application can get trapped in an infinite loop.
/// seealso:
/// <a href="https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/TextStorageLayer/Tasks/TrackingSize.html#//apple_ref/doc/uid/20000927-CJBBIAAF">Tracking the Size of a Text View</a>
@property (nonatomic) BOOL heightTracksTextView;
/// A Boolean that controls whether the receiver changes its height to fit the height of its text.
@property (nonatomic) BOOL isVerticallyResizable;
/// A Boolean that controls whether the text view highlights the currently selected line.
@property (nonatomic) BOOL highlightSelectedLine;
/// The highlight color of the selected line.
/// Note: Needs <code>highlightSelectedLine</code> to be set to <code>true</code>
@property (nonatomic, strong) NSColor * _Nonnull selectedLineHighlightColor;
/// The background color of a text selection.
@property (nonatomic, strong) NSColor * _Nonnull selectionBackgroundColor;
/// The text view’s background color
@property (nonatomic, strong) NSColor * _Nullable backgroundColor;
/// A Boolean value that indicates whether the receiver allows its background color to change.
@property (nonatomic) BOOL allowsDocumentBackgroundColorChange;
/// An action method used to set the background color.
- (void)changeDocumentBackgroundColor:(id _Nullable)sender;
/// The semantic meaning for a text input area.
@property (nonatomic) NSTextContentType _Nullable contentType;
/// A Boolean value that indicates whether the receiver allows undo.
/// <code>true</code> if the receiver allows undo, otherwise <code>false</code>. Default <code>true</code>.
@property (nonatomic) BOOL allowsUndo;
/// The attributes used to draw marked text.
/// Text color, background color, and underline are the only supported attributes for marked text.
@property (nonatomic, copy) NSDictionary<NSAttributedStringKey, id> * _Nonnull markedTextAttributes;
/// The manager that lays out text for the text view’s text container.
@property (nonatomic, readonly, strong) NSTextLayoutManager * _Nonnull textLayoutManager;
/// The text view’s text storage object.
@property (nonatomic, readonly, strong) NSTextContentManager * _Nonnull textContentManager;
/// A Boolean value that indicates whether the receiver has continuous spell checking enabled.
/// true if the object has continuous spell-checking enabled; otherwise, false.
@property (nonatomic) BOOL isContinuousSpellCheckingEnabled;
/// Enables and disables grammar checking.
/// If true, grammar checking is enabled; if false, it is disabled.
@property (nonatomic) BOOL isGrammarCheckingEnabled;
/// A Boolean value that indicates whether the text view supplies autocompletion suggestions as the user types.
@property (nonatomic) BOOL isAutomaticTextCompletionEnabled;
/// A Boolean value that indicates whether automatic spelling correction is enabled.
@property (nonatomic) BOOL isAutomaticSpellingCorrectionEnabled;
/// A Boolean value that indicates whether automatic text replacement is enabled.
@property (nonatomic) BOOL isAutomaticTextReplacementEnabled;
/// A Boolean value that enables and disables automatic quotation mark substitution.
@property (nonatomic) BOOL isAutomaticQuoteSubstitutionEnabled;
@property (nonatomic, readonly, getter=isFlipped) BOOL flipped;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) NSMenu * _Nullable defaultMenu;)
+ (NSMenu * _Nullable)defaultMenu SWIFT_WARN_UNUSED_RESULT;
/// Initializes a text view.
/// \param frameRect The frame rectangle of the text view.
///
- (nonnull instancetype)initWithFrame:(NSRect)frameRect OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)coder OBJC_DESIGNATED_INITIALIZER SWIFT_UNAVAILABLE;
- (void)resetCursorRects;
- (void)viewDidChangeEffectiveAppearance;
- (void)viewDidMoveToWindow;
- (NSView * _Nullable)hitTest:(NSPoint)point SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) BOOL canBecomeKeyView;
@property (nonatomic, readonly) BOOL needsPanelToBecomeKey;
@property (nonatomic, readonly) BOOL acceptsFirstResponder;
- (BOOL)becomeFirstResponder SWIFT_WARN_UNUSED_RESULT;
- (BOOL)resignFirstResponder SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic, readonly) NSSize intrinsicContentSize;
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, getter=isCompatibleWithResponsiveScrolling) BOOL compatibleWithResponsiveScrolling;)
+ (BOOL)isCompatibleWithResponsiveScrolling SWIFT_WARN_UNUSED_RESULT;
- (void)prepareContentInRect:(NSRect)rect;
- (void)drawRect:(NSRect)dirtyRect;
- (void)setFrameOrigin:(NSPoint)newOrigin;
- (void)setFrameSize:(NSSize)newSize;
- (void)viewDidEndLiveResize;
- (void)layout;
@end

@protocol NSDraggingInfo;
@interface STTextView (SWIFT_EXTENSION(STTextView))
- (void)concludeDragOperation:(id <NSDraggingInfo> _Nullable)sender;
@end

@interface STTextView (SWIFT_EXTENSION(STTextView))
/// Adds the underline attribute to the selected text attributes if absent; removes the attribute if present.
/// If there is a selection and the first character of the selected range has any form of underline on it,
/// or if there is no selection and the typing attributes have any form of underline, then underline is removed;
/// otherwise a single simple underline is added.
- (void)underline:(id _Nullable)sender;
@end

@interface STTextView (SWIFT_EXTENSION(STTextView))
/// Yanking means reinserting text previously killed. The usual way to move or copy text is to kill it and then yank it elsewhere.
/// https://www.gnu.org/software/emacs/manual/html_node/emacs/Yanking.html
- (void)yank:(id _Nullable)sender;
@end

@interface STTextView (SWIFT_EXTENSION(STTextView)) <NSChangeSpelling>
- (void)changeSpelling:(id _Nullable)sender;
@end

@class NSColorPanel;
@interface STTextView (SWIFT_EXTENSION(STTextView)) <NSColorChanging>
- (void)changeColor:(NSColorPanel * _Nullable)colorPanel;
@end

@interface STTextView (SWIFT_EXTENSION(STTextView)) <NSIgnoreMisspelledWords>
- (void)ignoreSpelling:(id _Nullable)sender;
@end

@class NSMenuItem;
@interface STTextView (SWIFT_EXTENSION(STTextView)) <NSMenuItemValidation>
- (BOOL)validateMenuItem:(NSMenuItem * _Nonnull)menuItem SWIFT_WARN_UNUSED_RESULT;
@end

@protocol NSTextLocation;
@class NSTextElement;
@class NSTextLayoutFragment;
@interface STTextView (SWIFT_EXTENSION(STTextView)) <NSTextLayoutManagerDelegate>
- (NSTextLayoutFragment * _Nonnull)textLayoutManager:(NSTextLayoutManager * _Nonnull)textLayoutManager textLayoutFragmentForLocation:(id <NSTextLocation> _Nonnull)location inTextElement:(NSTextElement * _Nonnull)textElement SWIFT_WARN_UNUSED_RESULT;
@end

@protocol NSValidatedUserInterfaceItem;
@interface STTextView (SWIFT_EXTENSION(STTextView)) <NSUserInterfaceValidations>
- (BOOL)validateUserInterfaceItem:(id <NSValidatedUserInterfaceItem> _Nonnull)item SWIFT_WARN_UNUSED_RESULT;
@end

@class NSFontPanel;
@interface STTextView (SWIFT_EXTENSION(STTextView))
/// This action method changes the font of the selection for a rich text object, or of all text for a plain text object.
- (void)changeFont:(id _Nullable)sender;
- (NSFontPanelModeMask)validModesForFontPanel:(NSFontPanel * _Nonnull)fontPanel SWIFT_WARN_UNUSED_RESULT;
@end

@class NSEvent;
@interface STTextView (SWIFT_EXTENSION(STTextView))
- (void)keyDown:(NSEvent * _Nonnull)event;
- (BOOL)performKeyEquivalent:(NSEvent * _Nonnull)event SWIFT_WARN_UNUSED_RESULT;
@end

@interface STTextView (SWIFT_EXTENSION(STTextView))
/// Performs a find panel action specified by the sender’s tag.
/// This is the generic action method for the find menu and find panel, and can be overridden to implement a custom find panel.
/// See NSTextFinder.Action for list of possible tags
- (void)performFindPanelAction:(id _Nullable)sender;
/// Performs all find oriented actions.
/// Before OS X v10.7, the default action for these menu items was performFindPanelAction(_:)
- (void)performTextFinderAction:(id _Nullable)sender;
@end

@interface STTextView (SWIFT_EXTENSION(STTextView))
/// Speaks the selected text, or all text if no selection.
- (void)startSpeaking:(id _Nullable)sender;
/// Stops the speaking of text.
- (void)stopSpeaking:(id _Nullable)sender;
@end

@class NSDraggingSession;
@interface STTextView (SWIFT_EXTENSION(STTextView)) <NSDraggingSource>
- (NSDragOperation)draggingSession:(NSDraggingSession * _Nonnull)session sourceOperationMaskForDraggingContext:(NSDraggingContext)context SWIFT_WARN_UNUSED_RESULT;
- (void)draggingSession:(NSDraggingSession * _Nonnull)session endedAtPoint:(NSPoint)screenPoint operation:(NSDragOperation)operation;
@end

@interface STTextView (SWIFT_EXTENSION(STTextView)) <NSTextLayoutOrientationProvider>
@property (nonatomic, readonly) NSTextLayoutOrientation layoutOrientation;
@end

@interface STTextView (SWIFT_EXTENSION(STTextView))
- (void)capitalizeWord:(id _Nullable)sender;
- (void)lowercaseWord:(id _Nullable)sender;
- (void)uppercaseWord:(id _Nullable)sender;
@end

@interface STTextView (SWIFT_EXTENSION(STTextView))
/// Supporting Autocomplete
/// see NSStandardKeyBindingResponding
- (void)complete:(id _Nullable)sender;
- (void)cancelOperation:(id _Nullable)sender;
@end

@class NSUndoManager;
@interface STTextView (SWIFT_EXTENSION(STTextView))
@property (nonatomic, readonly, strong) NSUndoManager * _Nullable undoManager;
@end

@class NSTextViewportLayoutController;
@interface STTextView (SWIFT_EXTENSION(STTextView)) <NSTextViewportLayoutControllerDelegate>
- (CGRect)viewportBoundsForTextViewportLayoutController:(NSTextViewportLayoutController * _Nonnull)textViewportLayoutController SWIFT_WARN_UNUSED_RESULT;
- (void)textViewportLayoutControllerWillLayout:(NSTextViewportLayoutController * _Nonnull)textViewportLayoutController;
- (void)textViewportLayoutController:(NSTextViewportLayoutController * _Nonnull)textViewportLayoutController configureRenderingSurfaceForTextLayoutFragment:(NSTextLayoutFragment * _Nonnull)textLayoutFragment;
- (void)textViewportLayoutControllerDidLayout:(NSTextViewportLayoutController * _Nonnull)textViewportLayoutController;
@end

@interface STTextView (SWIFT_EXTENSION(STTextView))
- (void)copy:(id _Nullable)sender;
- (void)paste:(id _Nullable)sender;
- (void)pasteAsPlainText:(id _Nullable)sender;
/// This action method inserts the contents of the pasteboard into the receiver’s text as rich text, maintaining its attributes.
- (void)pasteAsRichText:(id _Nullable)sender;
- (void)cut:(id _Nullable)sender;
- (void)delete:(id _Nullable)sender;
@end

@interface STTextView (SWIFT_EXTENSION(STTextView))
- (void)mouseDown:(NSEvent * _Nonnull)event;
- (void)mouseUp:(NSEvent * _Nonnull)event;
- (void)mouseDragged:(NSEvent * _Nonnull)event;
- (void)mouseMoved:(NSEvent * _Nonnull)event;
- (void)rightMouseDown:(NSEvent * _Nonnull)event;
- (NSMenu * _Nullable)menuForEvent:(NSEvent * _Nonnull)event SWIFT_WARN_UNUSED_RESULT;
@end

@class NSPasteboard;
@interface STTextView (SWIFT_EXTENSION(STTextView)) <NSServicesMenuRequestor>
/// The types this text view can read immediately from the pasteboard.
@property (nonatomic, readonly, copy) NSArray<NSPasteboardType> * _Nonnull readablePasteboardTypes;
/// The pasteboard types that can be provided from the current selection.
@property (nonatomic, readonly, copy) NSArray<NSPasteboardType> * _Nonnull writablePasteboardTypes;
/// Reads data of the given type from the specified pasteboard.
- (BOOL)readSelectionFrom:(NSPasteboard * _Nonnull)pboard type:(NSPasteboardType _Nonnull)type SWIFT_WARN_UNUSED_RESULT;
/// Writes the current selection to the specified pasteboard under each given type.
- (BOOL)writeSelectionToPasteboard:(NSPasteboard * _Nonnull)pboard types:(NSArray<NSPasteboardType> * _Nonnull)types SWIFT_WARN_UNUSED_RESULT;
/// Returns <code>self</code> if the text view can provide and accept the specified data types, or nil if it can’t
- (id _Nullable)validRequestorForSendType:(NSPasteboardType _Nullable)sendType returnType:(NSPasteboardType _Nullable)returnType SWIFT_WARN_UNUSED_RESULT;
@end

@interface STTextView (SWIFT_EXTENSION(STTextView))
- (void)insertLineBreak:(id _Nullable)sender;
- (void)insertTab:(id _Nullable)sender;
- (void)insertBacktab:(id _Nullable)sender;
- (void)insertTabIgnoringFieldEditor:(id _Nullable)sender;
- (void)insertParagraphSeparator:(id _Nullable)sender;
- (void)insertNewline:(id _Nullable)sender;
- (void)insertNewlineIgnoringFieldEditor:(id _Nullable)sender;
- (void)insertText:(id _Nonnull)insertString;
@end

@interface STTextView (SWIFT_EXTENSION(STTextView))
- (void)centerSelectionInVisibleArea:(id _Nullable)sender;
- (void)pageUp:(id _Nullable)sender;
- (void)pageUpAndModifySelection:(id _Nullable)sender;
- (void)pageDown:(id _Nullable)sender;
- (void)pageDownAndModifySelection:(id _Nullable)sender;
- (void)scrollPageDown:(id _Nullable)sender;
- (void)scrollPageUp:(id _Nullable)sender;
- (void)scrollToBeginningOfDocument:(id _Nullable)sender;
- (void)scrollToEndOfDocument:(id _Nullable)sender;
@end

@interface STTextView (SWIFT_EXTENSION(STTextView))
/// This action method shows or hides the ruler, if the receiver is enclosed in a scroll view.
- (void)toggleRuler:(id _Nullable)sender;
- (CGFloat)rulerView:(NSRulerView * _Nonnull)ruler willAddMarker:(NSRulerMarker * _Nonnull)marker atLocation:(CGFloat)location SWIFT_WARN_UNUSED_RESULT;
- (BOOL)rulerView:(NSRulerView * _Nonnull)ruler shouldAddMarker:(NSRulerMarker * _Nonnull)marker SWIFT_WARN_UNUSED_RESULT;
- (void)rulerView:(NSRulerView * _Nonnull)ruler didAddMarker:(NSRulerMarker * _Nonnull)marker;
- (void)rulerView:(NSRulerView * _Nonnull)ruler didRemoveMarker:(NSRulerMarker * _Nonnull)marker;
- (CGFloat)rulerView:(NSRulerView * _Nonnull)ruler locationForPoint:(NSPoint)point SWIFT_WARN_UNUSED_RESULT;
- (void)rulerView:(NSRulerView * _Nonnull)ruler handleMouseDown:(NSEvent * _Nonnull)event;
@end

@interface STTextView (SWIFT_EXTENSION(STTextView))
- (void)deleteForward:(id _Nullable)sender;
- (void)deleteBackward:(id _Nullable)sender;
- (void)deleteBackwardByDecomposingPreviousCharacter:(id _Nullable)sender;
- (void)deleteWordBackward:(id _Nullable)sender;
- (void)deleteWordForward:(id _Nullable)sender;
- (void)deleteToBeginningOfLine:(id _Nullable)sender;
- (void)deleteToEndOfLine:(id _Nullable)sender;
- (void)deleteToBeginningOfParagraph:(id _Nullable)sender;
- (void)deleteToEndOfParagraph:(id _Nullable)sender;
@end

@interface STTextView (SWIFT_EXTENSION(STTextView)) <NSTextCheckingClient>
- (NSAttributedString * _Nullable)annotatedSubstringForProposedRange:(NSRange)range actualRange:(NSRangePointer _Nullable)actualRange SWIFT_WARN_UNUSED_RESULT;
- (void)setAnnotations:(NSDictionary<NSAttributedStringKey, NSString *> * _Nonnull)annotations range:(NSRange)range;
- (void)addAnnotations:(NSDictionary<NSAttributedStringKey, NSString *> * _Nonnull)annotations range:(NSRange)range;
- (void)removeAnnotation:(NSAttributedStringKey _Nonnull)annotationName range:(NSRange)range;
- (void)replaceCharactersInRange:(NSRange)range withAnnotatedString:(NSAttributedString * _Nonnull)annotatedString;
- (void)selectAndShowRange:(NSRange)range;
- (NSView * _Nullable)viewForRange:(NSRange)range firstRect:(NSRectPointer _Nullable)firstRect actualRange:(NSRangePointer _Nullable)actualRange SWIFT_WARN_UNUSED_RESULT;
@end

@interface STTextView (SWIFT_EXTENSION(STTextView)) <NSTextInputClient>
- (NSRange)selectedRange SWIFT_WARN_UNUSED_RESULT;
/// Replaces a specified range in the receiver’s text storage with the given string and sets the selection.
/// If there is no marked text, the current selection is replaced. If there is no selection, the string is inserted at the insertion point.
/// When string is an NSString, the receiver is expected to render the marked text with distinguishing appearance (i.e. NSTextView renders with -markedTextAttributes).
/// \param string The string to insert. Can be either an NSString or NSAttributedString instance.
///
/// \param selectedRange The range to set as the selection, computed from the beginning of the inserted string.
///
/// \param replacementRange The range to replace, computed from the beginning of the marked text.
///
- (void)setMarkedText:(id _Nonnull)string selectedRange:(NSRange)selectedRange replacementRange:(NSRange)replacementRange;
/// The receiver unmarks the marked text. If no marked text, the invocation of this method has no effect.
/// The receiver removes any marking from pending input text and disposes of the marked text as it wishes.
/// The text view should accept the marked text as if it had been inserted normally.
/// If there is no marked text, the invocation of this method has no effect.
- (void)unmarkText;
/// Returns the marked range. Returns {NSNotFound, 0} if no marked range.
/// The returned range measures from the start of the receiver’s text storage.
/// The return value’s location is NSNotFound and its length is 0 if and only if hasMarkedText() returns false.
- (NSRange)markedRange SWIFT_WARN_UNUSED_RESULT;
/// Returns whether or not the receiver has marked text.
- (BOOL)hasMarkedText SWIFT_WARN_UNUSED_RESULT;
- (NSAttributedString * _Nullable)attributedSubstringForProposedRange:(NSRange)range actualRange:(NSRangePointer _Nullable)actualRange SWIFT_WARN_UNUSED_RESULT;
- (NSAttributedString * _Nonnull)attributedString SWIFT_WARN_UNUSED_RESULT;
/// Returns an array of attribute names recognized by the receiver.
/// Returns an empty array if no attributes are supported.
- (NSArray<NSAttributedStringKey> * _Nonnull)validAttributesForMarkedText SWIFT_WARN_UNUSED_RESULT;
- (NSRect)firstRectForCharacterRange:(NSRange)range actualRange:(NSRangePointer _Nullable)actualRange SWIFT_WARN_UNUSED_RESULT;
- (NSUInteger)characterIndexForPoint:(CGPoint)point SWIFT_WARN_UNUSED_RESULT;
- (void)insertText:(id _Nonnull)string replacementRange:(NSRange)replacementRange;
@end

@interface STTextView (SWIFT_EXTENSION(STTextView)) <NSTextInputTraits>
@property (nonatomic) NSTextInputTraitType spellCheckingType;
@property (nonatomic) NSTextInputTraitType autocorrectionType;
@property (nonatomic) NSTextInputTraitType grammarCheckingType;
@property (nonatomic) NSTextInputTraitType textCompletionType;
@property (nonatomic) NSTextInputTraitType textReplacementType;
@property (nonatomic) NSTextInputTraitType smartQuotesType;
@end

@interface STTextView (SWIFT_EXTENSION(STTextView))
- (BOOL)isAccessibilityElement SWIFT_WARN_UNUSED_RESULT;
- (BOOL)isAccessibilityEnabled SWIFT_WARN_UNUSED_RESULT;
- (NSAccessibilityRole _Nullable)accessibilityRole SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)accessibilityRoleDescription SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)accessibilityLabel SWIFT_WARN_UNUSED_RESULT;
- (id _Nullable)accessibilityValue SWIFT_WARN_UNUSED_RESULT;
- (void)setAccessibilityValue:(id _Nullable)accessibilityValue;
- (NSAttributedString * _Nullable)accessibilityAttributedStringForRange:(NSRange)range SWIFT_WARN_UNUSED_RESULT;
- (NSRange)accessibilityVisibleCharacterRange SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)accessibilityStringForRange:(NSRange)range SWIFT_WARN_UNUSED_RESULT;
- (NSInteger)accessibilityNumberOfCharacters SWIFT_WARN_UNUSED_RESULT;
- (NSString * _Nullable)accessibilitySelectedText SWIFT_WARN_UNUSED_RESULT;
- (NSRange)accessibilitySelectedTextRange SWIFT_WARN_UNUSED_RESULT;
- (void)setAccessibilitySelectedTextRange:(NSRange)accessibilitySelectedTextRange;
@end

@interface STTextView (SWIFT_EXTENSION(STTextView))
@property (nonatomic, readonly) NSInteger spellCheckerDocumentTag;
- (void)checkTextInDocument:(id _Nullable)sender;
- (void)checkTextInSelection:(id _Nullable)sender;
- (void)checkTextIn:(NSRange)range types:(NSTextCheckingTypes)checkingTypes options:(NSDictionary<NSTextCheckingOptionKey, id> * _Nonnull)options;
- (void)checkSpelling:(id _Nullable)sender;
- (void)toggleContinuousSpellChecking:(id _Nullable)sender;
- (void)toggleGrammarChecking:(id _Nullable)sender;
- (void)toggleAutomaticSpellingCorrection:(id _Nullable)sender;
- (void)toggleAutomaticTextCompletion:(id _Nullable)sender;
- (void)toggleAutomaticQuoteSubstitution:(id _Nullable)sender;
- (void)showGuessPanel:(id _Nullable)sender;
- (void)orderFrontSubstitutionsPanel:(id _Nullable)sender;
@end

@interface STTextView (SWIFT_EXTENSION(STTextView))
- (void)selectAll:(id _Nullable)sender;
- (void)selectLine:(id _Nullable)sender;
- (void)selectWord:(id _Nullable)sender;
- (void)selectParagraph:(id _Nullable)sender;
- (void)moveLeft:(id _Nullable)sender;
- (void)moveLeftAndModifySelection:(id _Nullable)sender;
- (void)moveRight:(id _Nullable)sender;
- (void)moveRightAndModifySelection:(id _Nullable)sender;
- (void)moveUp:(id _Nullable)sender;
- (void)moveUpAndModifySelection:(id _Nullable)sender;
- (void)moveDown:(id _Nullable)sender;
- (void)moveDownAndModifySelection:(id _Nullable)sender;
- (void)moveForward:(id _Nullable)sender;
- (void)moveForwardAndModifySelection:(id _Nullable)sender;
- (void)moveBackward:(id _Nullable)sender;
- (void)moveBackwardAndModifySelection:(id _Nullable)sender;
- (void)moveWordLeft:(id _Nullable)sender;
- (void)moveWordLeftAndModifySelection:(id _Nullable)sender;
- (void)moveWordRight:(id _Nullable)sender;
- (void)moveWordRightAndModifySelection:(id _Nullable)sender;
- (void)moveWordForward:(id _Nullable)sender;
- (void)moveWordForwardAndModifySelection:(id _Nullable)sender;
- (void)moveWordBackward:(id _Nullable)sender;
- (void)moveWordBackwardAndModifySelection:(id _Nullable)sender;
- (void)moveToBeginningOfLine:(id _Nullable)sender;
- (void)moveToBeginningOfLineAndModifySelection:(id _Nullable)sender;
- (void)moveToLeftEndOfLine:(id _Nullable)sender;
- (void)moveToLeftEndOfLineAndModifySelection:(id _Nullable)sender;
- (void)moveToEndOfLine:(id _Nullable)sender;
- (void)moveToEndOfLineAndModifySelection:(id _Nullable)sender;
- (void)moveToRightEndOfLine:(id _Nullable)sender;
- (void)moveToRightEndOfLineAndModifySelection:(id _Nullable)sender;
- (void)moveParagraphForwardAndModifySelection:(id _Nullable)sender;
- (void)moveParagraphBackwardAndModifySelection:(id _Nullable)sender;
- (void)moveToBeginningOfParagraph:(id _Nullable)sender;
- (void)moveToBeginningOfParagraphAndModifySelection:(id _Nullable)sender;
- (void)moveToEndOfParagraph:(id _Nullable)sender;
- (void)moveToEndOfParagraphAndModifySelection:(id _Nullable)sender;
- (void)moveToBeginningOfDocument:(id _Nullable)sender;
- (void)moveToBeginningOfDocumentAndModifySelection:(id _Nullable)sender;
- (void)moveToEndOfDocument:(id _Nullable)sender;
- (void)moveToEndOfDocumentAndModifySelection:(id _Nullable)sender;
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif
